//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecycleWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class RecyclableType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecyclableType()
        {
            this.RecyclableItems = new HashSet<RecyclableItem>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public decimal Rate { get; set; }

        [DisplayName("Minimum Kg")]
        public decimal MinKg { get; set; }

        [DisplayName("Maximum Kg")]
        public decimal MaxKg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecyclableItem> RecyclableItems { get; set; }
    }
}
